
  subgraph "Legend"
      style Legend fill: #ffffff,stroke:#ffffff
      style A fill: #027368,color:#ffffff
      style B fill: #0A4771,color:#ffffff
      A[Maintained Component]
      B[External Component]
    end